### ISSUE TITLE
Live tests failing on master 

### ISSUE THREAD

**Issue by timchaston** [mhenrixon/active_campaign#71]
Hi,

I put up a PR (#70) and found that a number of tests are broken on `master` if you delete the VCR cassettes.
Tests were run on an empty ActiveCampaign sandbox.

Rspec output:
[active_campaign-master-rspec-output-2020-07-15.txt](https://github.com/mhenrixon/active_campaign/files/4922957/active_campaign-master-rspec-output-2020-07-15.txt)

**Comment by mhenrixon** [comment]
If you remove the cassettes, you will have to focus one test at a time and run them until they pass. You also would have go in and delete things manually on your account. Most likely some contact, group or otherwise that is saved and not deleted.

I bet your account isn't as empty as you think it is :)

Anyway. this is what I tried to tell you before about how difficult it is to setup this test suite. Possibly it would be better to use mocking (at least for reliability of the test suite). I'd say Faraday stubs would be more reliable but... then we lose the possiblity of doing real tests which means they would also be less valuable. 

As a general note, don't delete cassettes except one at a time

**Comment by timchaston** [comment]
Thanks for the reply!

> As a general note, don't delete cassettes except one at a time

Haha, yeah, I was a bit heavy-handed in regenerating them all on my PR branch (in my defence, it has been a useful strategy in the past). Letting VCR do it's thing regenerated only 9 cassettes and everything is passing now after making a code fix (which was a lot easier to figure out without all the other stuff).
